### PR TITLE
FEATURE: Insertupdate receiver request

### PR DESCRIPTION
**Pull request by daniellienert**

### CODE REVIEW

**Comment by Nikdro** [comment]
Hi @daniellienert,

what is the need here for the new method? I can't see where it's used. Am I missing something?

**Comment by daniellienert** [comment]
@Nikdro, the method is not used anywhere in the package itself. We expose the CleverReach API endpoint `upsert` here to use it in the code of our own project.

**Comment by Nikdro** [comment]
Ah okay, got it. Good idea, thanks for the PR 👍

**Comment by Nikdro** [comment]
Now available in Version 2.0.1 🙂

**Comment by daniellienert** [comment]
Thanks :)

**Pull request merged**
